# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/add_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_dialog(object):
    def setupUi(self, add_dialog):
        add_dialog.setObjectName("add_dialog")
        add_dialog.resize(236, 241)
        add_dialog.setMinimumSize(QtCore.QSize(232, 203))
        self.verticalLayout = QtWidgets.QVBoxLayout(add_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.group_box = QtWidgets.QGroupBox(add_dialog)
        self.group_box.setObjectName("group_box")
        self.formLayout = QtWidgets.QFormLayout(self.group_box)
        self.formLayout.setObjectName("formLayout")
        self.name_label = QtWidgets.QLabel(self.group_box)
        self.name_label.setObjectName("name_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.name_label)
        self.name = QtWidgets.QLineEdit(self.group_box)
        self.name.setObjectName("name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name)
        self.type = QtWidgets.QComboBox(self.group_box)
        self.type.setMinimumSize(QtCore.QSize(125, 0))
        self.type.setObjectName("type")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Users/kevin/PycharmProjects/QuickBite/gui/assets/icons/icons/filter_breakfast.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.type.addItem(icon, "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Users/kevin/PycharmProjects/QuickBite/gui/assets/icons/icons/filter_lunch.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.type.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Users/kevin/PycharmProjects/QuickBite/gui/assets/icons/icons/filter_snacks.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.type.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Users/kevin/PycharmProjects/QuickBite/gui/assets/icons/icons/filter_softdrinks.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.type.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Users/kevin/PycharmProjects/QuickBite/gui/assets/icons/icons/filter_beverages.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.type.addItem(icon4, "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Users/kevin/PycharmProjects/QuickBite/gui/assets/icons/icons/filter_icecream.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.type.addItem(icon5, "")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.type)
        self.price_label = QtWidgets.QLabel(self.group_box)
        self.price_label.setObjectName("price_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.price_label)
        self.price = QtWidgets.QSpinBox(self.group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.price.sizePolicy().hasHeightForWidth())
        self.price.setSizePolicy(sizePolicy)
        self.price.setMinimumSize(QtCore.QSize(116, 0))
        self.price.setObjectName("price")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.price)
        self.quantity_label = QtWidgets.QLabel(self.group_box)
        self.quantity_label.setObjectName("quantity_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.quantity_label)
        self.quantity = QtWidgets.QSpinBox(self.group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quantity.sizePolicy().hasHeightForWidth())
        self.quantity.setSizePolicy(sizePolicy)
        self.quantity.setMinimumSize(QtCore.QSize(116, 0))
        self.quantity.setObjectName("quantity")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.quantity)
        self.available_label = QtWidgets.QLabel(self.group_box)
        self.available_label.setObjectName("available_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.available_label)
        self.available = QtWidgets.QCheckBox(self.group_box)
        self.available.setText("")
        self.available.setCheckable(True)
        self.available.setChecked(True)
        self.available.setObjectName("available")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.available)
        self.type_label = QtWidgets.QLabel(self.group_box)
        self.type_label.setObjectName("type_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.type_label)
        self.verticalLayout.addWidget(self.group_box)
        self.button_box = QtWidgets.QDialogButtonBox(add_dialog)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)

        self.retranslateUi(add_dialog)
        self.button_box.accepted.connect(add_dialog.accept) # type: ignore
        self.button_box.rejected.connect(add_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(add_dialog)

    def retranslateUi(self, add_dialog):
        _translate = QtCore.QCoreApplication.translate
        add_dialog.setWindowTitle(_translate("add_dialog", "Dialog"))
        self.group_box.setTitle(_translate("add_dialog", "Add item"))
        self.name_label.setText(_translate("add_dialog", "Name"))
        self.type.setCurrentText(_translate("add_dialog", "Breakfast"))
        self.type.setPlaceholderText(_translate("add_dialog", "Select"))
        self.type.setItemText(0, _translate("add_dialog", "Breakfast"))
        self.type.setItemText(1, _translate("add_dialog", "Lunch"))
        self.type.setItemText(2, _translate("add_dialog", "Snacks"))
        self.type.setItemText(3, _translate("add_dialog", "Soft Drinks"))
        self.type.setItemText(4, _translate("add_dialog", "Beverages"))
        self.type.setItemText(5, _translate("add_dialog", "Ice Cream"))
        self.price_label.setText(_translate("add_dialog", "Price"))
        self.price.setSuffix(_translate("add_dialog", " /-"))
        self.price.setPrefix(_translate("add_dialog", "Rs. "))
        self.quantity_label.setText(_translate("add_dialog", "Quantity"))
        self.quantity.setSuffix(_translate("add_dialog", " serves"))
        self.available_label.setText(_translate("add_dialog", "Available"))
        self.type_label.setText(_translate("add_dialog", "Type"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_dialog = QtWidgets.QDialog()
    ui = Ui_add_dialog()
    ui.setupUi(add_dialog)
    add_dialog.show()
    sys.exit(app.exec_())
