# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/add_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_dialog(object):
    def setupUi(self, add_dialog):
        add_dialog.setObjectName("add_dialog")
        add_dialog.resize(240, 203)
        add_dialog.setMinimumSize(QtCore.QSize(232, 203))
        self.verticalLayout = QtWidgets.QVBoxLayout(add_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.group_box = QtWidgets.QGroupBox(add_dialog)
        self.group_box.setObjectName("group_box")
        self.formLayout = QtWidgets.QFormLayout(self.group_box)
        self.formLayout.setObjectName("formLayout")
        self.name_label = QtWidgets.QLabel(self.group_box)
        self.name_label.setObjectName("name_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.name_label)
        self.lineEdit = QtWidgets.QLineEdit(self.group_box)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.group_box)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.spinBox = QtWidgets.QSpinBox(self.group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setMinimumSize(QtCore.QSize(116, 0))
        self.spinBox.setObjectName("spinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.label_3 = QtWidgets.QLabel(self.group_box)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.spinBox_2 = QtWidgets.QSpinBox(self.group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_2.sizePolicy().hasHeightForWidth())
        self.spinBox_2.setSizePolicy(sizePolicy)
        self.spinBox_2.setMinimumSize(QtCore.QSize(116, 0))
        self.spinBox_2.setObjectName("spinBox_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_2)
        self.label = QtWidgets.QLabel(self.group_box)
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.checkBox = QtWidgets.QCheckBox(self.group_box)
        self.checkBox.setText("")
        self.checkBox.setCheckable(True)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.checkBox)
        self.verticalLayout.addWidget(self.group_box)
        self.button_box = QtWidgets.QDialogButtonBox(add_dialog)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)

        self.retranslateUi(add_dialog)
        self.button_box.accepted.connect(add_dialog.accept) # type: ignore
        self.button_box.rejected.connect(add_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(add_dialog)

    def retranslateUi(self, add_dialog):
        _translate = QtCore.QCoreApplication.translate
        add_dialog.setWindowTitle(_translate("add_dialog", "Dialog"))
        self.group_box.setTitle(_translate("add_dialog", "Add item"))
        self.name_label.setText(_translate("add_dialog", "Name"))
        self.label_2.setText(_translate("add_dialog", "Price"))
        self.spinBox.setSuffix(_translate("add_dialog", " /-"))
        self.spinBox.setPrefix(_translate("add_dialog", "Rs. "))
        self.label_3.setText(_translate("add_dialog", "Quantity"))
        self.spinBox_2.setSuffix(_translate("add_dialog", " serves"))
        self.label.setText(_translate("add_dialog", "Available"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_dialog = QtWidgets.QDialog()
    ui = Ui_add_dialog()
    ui.setupUi(add_dialog)
    add_dialog.show()
    sys.exit(app.exec_())
